"""Static inventory of literal recipe tables; does not execute attached Lua."""
import re,json,csv,collections,argparse
from pathlib import Path
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--reference-dump', type=Path, help='Optional Factorio data-raw-dump.json to compare names against')
args=parser.parse_args()
mod=Path(__file__).resolve().parents[2]
root=mod/'docs/data'
def clean(s):
 s=re.sub(r'--\[\[.*?\]\]',lambda m:'\n'*m[0].count('\n'),s,flags=re.S)
 return re.sub(r'--[^\n]*','',s)
def table(s,start):
 depth=0; quoted=False; escape=False
 for i in range(start,len(s)):
  c=s[i]
  if quoted:
   if escape:escape=False
   elif c=='\\':escape=True
   elif c=='"':quoted=False
  elif c=='"':quoted=True
  elif c=='{':depth+=1
  elif c=='}':
   depth-=1
   if depth==0:return s[start:i+1]
 raise ValueError('unbalanced')
def field(s,key,default=None):
 m=re.search(r'\b'+key+r'\s*=\s*("[^"]*"|[0-9.]+)',s)
 if not m:return default
 v=m[1]
 return v[1:-1] if v.startswith('"') else float(v)
def amounts(s,key):
 m=re.search(r'\b'+key+r'\s*=\s*{',s)
 if not m:return []
 t=table(s,m.end()-1)
 out=[]
 for x in re.findall(r'\{([^{}]+)\}',t):
  if 'name' in x:out.append({'name':field(x,'name'),'amount':field(x,'amount'),'type':field(x,'type','item')})
  else:
   n,a=re.fullmatch(r'\s*"([^"]+)"\s*,\s*([0-9.]+)\s*,?\s*',x).groups()
   out.append({'name':n,'amount':float(a),'type':'item'})
 return out
names={}
for f in sorted((mod/'locale/en').glob('*.cfg')):
 section=''
 for l in f.read_text().splitlines():
  if l.startswith('['):section=l.strip()
  elif '=' in l and section in ('[item-name]','[entity-name]','[equipment-name]'):
   k,v=l.split('=',1)
   if v and k not in names:names[k]=v.strip()
names.update({'y-unicomp-a2':'Unicomp (UC-A2)','y-richdust':'Rich dust','ypfw_trader_sign':'Trader Sign'})
recipes=[]; prototypes=[]
for f in sorted((mod/'prototypes').rglob('*.lua')):
 s=clean(f.read_text()); previous_end=-1
 for m in re.finditer(r'\{\s*type\s*=\s*"([^"]+)"\s*,\s*name\s*=\s*"([^"]+)"',s):
  if m.start()<previous_end:continue
  t=table(s,m.start()); previous_end=m.start()+len(t)
  typ,n=m.groups(); prototypes.append((typ,n))
  if typ!='recipe':continue
  t=table(s,m.start()); results=amounts(t,'results')
  if not results and field(t,'result'):results=[{'name':field(t,'result'),'amount':field(t,'result_count',1),'type':'item'}]
  recipes.append(dict(name=n,category=field(t,'category','crafting'),seconds=field(t,'energy_required',0.5),ingredients=amounts(t,'ingredients'),results=results,source=str(f.relative_to(mod)),line=s[:m.start()].count('\n')+1))
recipes.sort(key=lambda r:r['name'])
(root/'recipes.json').write_text(json.dumps(recipes,indent=2))
def fmt(xs):return ' + '.join(f"{x['amount']:g} {names.get(x['name'],x['name'])} [{x['name']}]" for x in xs)
with (root/'recipe-inventory.csv').open('w') as f:
 w=csv.writer(f,lineterminator="\n");w.writerow(['Recipe ID','Category','Base seconds','Ingredients','Products','Source file','Line'])
 for r in recipes:w.writerow([r['name'],r['category'],r['seconds'],fmt(r['ingredients']),fmt(r['results']),r['source'],r['line']])
def md_escape(value):
 return str(value).replace('|','\\|').replace('\n',' ')
lines=['# Complete active recipe catalog', '',
 'Generated by `docs/tools/extract_inventory.py` from the original 0.4.15 source. Active declarations are not proof of in-game reachability. Quantities are per execution; seconds are base crafting time. Internal item names are retained for traceability.', '',
 '| Recipe | Category | Base seconds | Ingredients | Products | Source |',
 '|---|---|---:|---|---|---|']
for r in recipes:
 lines.append('| '+ ' | '.join([md_escape(r['name']),md_escape(r['category']),f"{r['seconds']:g}",md_escape(fmt(r['ingredients'])),md_escape(fmt(r['results'])),f"[{r['source']}:{r['line']}](../{r['source']}#L{r['line']})"])+' |')
(mod/'docs/recipe-catalog.md').write_text('\n'.join(lines)+'\n')
print('Active literal recipe count:',len(recipes));print('Categories:',dict(collections.Counter(r['category'] for r in recipes)))
print('Prototype types:',dict(collections.Counter(t for t,n in prototypes)))
produced={x['name'] for r in recipes for x in r['results']}
owned={n for t,n in prototypes if t in ['item','gun','ammo','armor']}
print('Owned items with no recipe output:',sorted(owned-produced))
summary={
 'scope':'Static literal-table inventory of yi_pfw 0.4.15; not a Factorio load test or a general Lua parser.',
 'active_recipe_count':len(recipes),
 'recipe_categories':dict(sorted(collections.Counter(r['category'] for r in recipes).items())),
 'prototype_types':dict(sorted(collections.Counter(t for t,n in prototypes).items())),
 'owned_items_without_recipe_output':sorted(owned-produced),
}
(root/'inventory-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
if args.reference_dump:
 dump=json.loads(args.reference_dump.read_text())
 # Name-level comparison only; existence is not proof of matching type or semantics.
 external={x['name'] for r in recipes for x in r['ingredients']+r['results']}-owned
 allnames={n for vs in dump.values() if isinstance(vs,dict) for n in vs}
 print('External recipe references absent from reference dump:',sorted(external-allnames))
 print('PFW prototype names overlapping reference dump:',[(t,n) for t,n in prototypes if n in dump.get(t,{})])
